### ISSUE TITLE
Shift for any shortcut is probably a bad idea and should be changed

### ISSUE THREAD

**Issue by olymk2** [agusmakmun/dracos-markdown-editor#4]
Currently I cant type a capital S because its a shortcut and gets replaced with ~~ ~~ I assume I cant use a capital U either for a similar reason.

Can the shortcuts be turned of as a quick fix ?

**Comment by agusmakmun** [comment]
It because this editor used it commands for _Underscores_ and _Strikethrough_.

```js
editor.commands.addCommand({
    name: 'markdownToUnderscores',
    bindKey: {win: 'Shift-U', mac: 'Option-U'},
    exec: function(editor) {
        markdownToUnderscores()
    },
    readOnly: true
});
editor.commands.addCommand({
    name: 'markdownToStrikethrough',
    bindKey: {win: 'Shift-S', mac: 'Option-S'},
    exec: function(editor) {
        markdownToStrikethrough()
    },
    readOnly: true
});
```

Perhaps next update I'll change it to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> for <ins>Underscores</ins>, and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> for <del>Strikethrough</del>, See also this [previous release: v1.1.6](https://github.com/agusmakmun/dracos-markdown-editor/releases/tag/v1.1.6)

Thank you so much for this issue... :+1:

**Comment by olymk2** [comment]
Yeah that would be great, and definitely needed to allow upper case characters :)

**Comment by olymk2** [comment]
great thanks for fixing that :)
